import { MetadataRoute } from "next";
import { blogPosts } from "@/lib/blog";

const BASE = "https://flexcommerce.co.uk";
const NOW = new Date().toISOString();

const staticRoutes: MetadataRoute.Sitemap = [
  { url: BASE, lastModified: NOW, changeFrequency: "weekly", priority: 1.0 },

  // Core service pages
  { url: `${BASE}/shopify-services`,           lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-plus`,               lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-theme-development`,  lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-app-development`,    lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-integrations`,       lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
  { url: `${BASE}/shopify-migration`,          lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-seo`,                lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-speed-optimisation`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
  { url: `${BASE}/shopify-store-audit`,        lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
  { url: `${BASE}/shopify-support`,            lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
  { url: `${BASE}/shopify-maintenance`,        lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
  { url: `${BASE}/shopify-ai`,                 lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
  { url: `${BASE}/automations`,                lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/ecommerce-agency`,           lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },

  // Migration pages
  { url: `${BASE}/woocommerce-to-shopify-migration`,  lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/magento-to-shopify-migration`,      lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/bigcommerce-to-shopify-migration`,  lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
  { url: `${BASE}/squarespace-to-shopify-migration`,  lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/webflow-to-shopify-migration`,      lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/salesforce-to-shopify-migration`,   lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },

  // Location pages
  { url: `${BASE}/shopify-agency-manchester`,  lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-agency-liverpool`,   lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-agency-london`,      lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
  { url: `${BASE}/shopify-agency-birmingham`,  lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/shopify-agency-leeds`,       lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/shopify-agency-bristol`,     lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/shopify-agency-edinburgh`,   lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/shopify-agency-glasgow`,     lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/shopify-agency-newcastle`,   lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/shopify-agency-cambridge`,   lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },

  // Company pages
  { url: `${BASE}/about`,     lastModified: NOW, changeFrequency: "monthly", priority: 0.6 },
  { url: `${BASE}/work`,      lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/pricing`,   lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/partners`,  lastModified: NOW, changeFrequency: "monthly", priority: 0.5 },
  { url: `${BASE}/contact`,   lastModified: NOW, changeFrequency: "yearly",  priority: 0.6 },
  { url: `${BASE}/quote`,     lastModified: NOW, changeFrequency: "yearly",  priority: 0.8 },
  { url: `${BASE}/resources`, lastModified: NOW, changeFrequency: "weekly",  priority: 0.7 },
  { url: `${BASE}/articles`,  lastModified: NOW, changeFrequency: "weekly",  priority: 0.8 },
  { url: `${BASE}/guides`,    lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/checklists`,lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
  { url: `${BASE}/privacy`,   lastModified: NOW, changeFrequency: "yearly",  priority: 0.3 },
  { url: `${BASE}/terms`,     lastModified: NOW, changeFrequency: "yearly",  priority: 0.3 },

  // Guide pages
  { url: `${BASE}/guides/how-to-add-cookie-consent-to-shopify`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-add-currency-converter-to-shopify`,        lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-add-custom-css-to-shopify`,                lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-add-custom-fonts-to-shopify`,              lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-add-products-to-shopify`,                  lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-add-reviews-to-shopify`,                   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-add-schema-markup-to-shopify`,             lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-add-trust-badges-to-shopify`,              lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-choose-shopify-apps`,                      lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-configure-shopify-checkout`,               lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-configure-shopify-shipping-rates`,         lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-connect-shopify-to-accounting-software`,   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-connect-shopify-to-google-merchant-center`,lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-shopify-announcement-bars`,         lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-shopify-collections`,               lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-shopify-discount-codes`,            lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-shopify-email-campaigns`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-shopify-landing-pages`,             lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-shopify-product-bundles`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-shopify-redirects`,                 lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-urgency-on-shopify`,                lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-create-wholesale-pricing-on-shopify`,      lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-customise-shopify-theme`,                  lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-handle-shopify-returns`,                   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-import-products-to-shopify`,               lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-integrate-shopify-with-erp`,               lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-make-shopify-gdpr-compliant`,              lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-manage-shopify-inventory`,                 lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-migrate-from-magento-to-shopify`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.7 },
  { url: `${BASE}/guides/how-to-migrate-from-woocommerce-to-shopify`,      lastModified: NOW, changeFrequency: "yearly", priority: 0.7 },
  { url: `${BASE}/guides/how-to-migrate-to-shopify-plus`,                  lastModified: NOW, changeFrequency: "yearly", priority: 0.7 },
  { url: `${BASE}/guides/how-to-offer-free-shipping-on-shopify`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-optimise-shopify-images-for-seo`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-optimise-shopify-product-images`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-optimise-shopify-product-pages-for-seo`,   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-optimise-your-shopify-store-for-speed`,    lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-read-shopify-analytics`,                   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-reduce-shopify-cart-abandonment`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-remove-unused-shopify-app-code`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-run-shopify-flash-sales`,                  lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-secure-your-shopify-store`,                lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-sell-internationally-on-shopify`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-facebook-pixel-on-shopify`,         lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-google-analytics-4-on-shopify`,     lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-klaviyo-on-shopify`,                lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-abandoned-cart-emails`,     lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-b2b`,                       lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-customer-accounts`,         lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-local-delivery`,            lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-markets`,                   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-navigation-menus`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-order-tracking`,            lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-payments`,                  lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-pos`,                       lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-product-variants`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-reports`,                   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-shopify-taxes`,                     lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-set-up-trade-accounts-on-shopify`,         lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-structure-shopify-urls-for-seo`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-track-shopify-conversions`,                lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-translate-your-shopify-store`,             lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-write-product-descriptions-that-sell`,     lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/guides/how-to-write-shopify-meta-descriptions`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },

  // Checklist pages
  { url: `${BASE}/checklists/magento-to-shopify-checklist`,               lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-abandoned-cart-checklist`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-app-audit-checklist`,                lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-b2b-wholesale-checklist`,            lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-black-friday-checklist`,             lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-checkout-optimisation-checklist`,    lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-cro-checklist`,                      lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-digital-products-checklist`,         lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-dropshipping-checklist`,             lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-email-marketing-checklist`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-facebook-ads-checklist`,             lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-flash-sale-checklist`,               lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-gdpr-checklist`,                     lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-google-shopping-checklist`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-holiday-checklist`,                  lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-homepage-checklist`,                 lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-launch-checklist`,                   lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-mobile-optimisation-checklist`,      lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-plus-migration-checklist`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-print-on-demand-checklist`,          lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-product-page-checklist`,             lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-security-checklist`,                 lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-seo-checklist`,                      lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/shopify-speed-optimisation-checklist`,       lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
  { url: `${BASE}/checklists/woocommerce-to-shopify-checklist`,           lastModified: NOW, changeFrequency: "yearly", priority: 0.6 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const articleRoutes: MetadataRoute.Sitemap = blogPosts.map((post) => ({
    url: `${BASE}/articles/${post.slug}`,
    lastModified: post.date,
    changeFrequency: "yearly",
    priority: 0.6,
  }));

  return [...staticRoutes, ...articleRoutes];
}
